"""
Preprocessing pipeline module for Task 1: Credit Scoring Model.
Builds complete scikit-learn Pipelines wrapping numerical scaling, categorical impositions, 
One-Hot Encoding, and stratified splits.
"""
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

from src.config import Config
from src.feature_engineering import FeatureEngineer

class Preprocessor:
    """
    Main preprocessing orchestrator.
    Builds, fits, and applies ColumnTransformer pipelines containing StandardScalers, 
    SimpleImputers, and OneHotEncoders.
    """
    def __init__(self, random_seed: int = Config.RANDOM_SEED):
        self.random_seed = random_seed
        self.pipeline = None
        self.is_fitted = False

    def build_pipeline(self) -> Pipeline:
        """
        Assembles scikit-learn steps into an end-to-end pipeline.
        Runs FeatureEngineer first, then passes the results to ColumnTransformer.
        """
        # Features mapping including engineered variables
        numerical_features = Config.NUMERICAL_FEATURES + ["credit_per_month", "credit_to_age_ratio"]
        categorical_features = Config.CATEGORICAL_FEATURES + ["age_group"]
        
        # 1. Numerical pipeline: Median Imputer followed by Standard Scaler
        numerical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ])
        
        # 2. Categorical pipeline: Replace missing values with 'unknown' and One-Hot Encode
        categorical_transformer = Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="constant", fill_value="unknown")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
        ])
        
        # 3. Assemble ColumnTransformer step
        preprocessor = ColumnTransformer(transformers=[
            ("num", numerical_transformer, numerical_features),
            ("cat", categorical_transformer, categorical_features)
        ])
        
        # 4. Create final pipeline wrapping Feature Engineering first
        self.pipeline = Pipeline(steps=[
            ("feature_engineer", FeatureEngineer()),
            ("preprocessor", preprocessor)
        ])
        
        return self.pipeline

    def fit(self, X: pd.DataFrame, y: pd.Series = None) -> 'Preprocessor':
        """
        Fits the complete preprocessing pipeline on training features.
        """
        if self.pipeline is None:
            self.build_pipeline()
            
        self.pipeline.fit(X, y)
        self.is_fitted = True
        return self

    def transform(self, X: pd.DataFrame) -> np.ndarray:
        """
        Applies pipeline feature engineering, imputation, encoding, and scaling 
        to return the processed float matrix.
        """
        if not self.is_fitted:
            raise ValueError("Preprocessor has not been fitted. Call fit() first.")
            
        return self.pipeline.transform(X)

    def fit_transform(self, X: pd.DataFrame, y: pd.Series = None) -> np.ndarray:
        """
        Fits and transforms in a single operation.
        """
        return self.fit(X, y).transform(X)

    def get_feature_names(self) -> list:
        """
        Returns feature column names corresponding to the transformed matrix.
        """
        if not self.is_fitted:
            raise ValueError("Preprocessor has not been fitted yet.")
            
        # Get column names generated by OneHotEncoder and StandardScaler inside ColumnTransformer
        preprocessor_step = self.pipeline.named_steps["preprocessor"]
        return list(preprocessor_step.get_feature_names_out())

def stratified_train_test_split(df: pd.DataFrame, target_col: str = Config.TARGET_COLUMN, 
                                test_size: float = Config.TEST_SIZE, 
                                random_state: int = Config.RANDOM_SEED):
    """
    Splits DataFrame features and targets, encodes target classes to binary labels, 
    and returns stratified train/test sets.
    """
    X = df.drop(columns=[target_col])
    
    # Map good credit risk to 0 (No Risk) and bad credit risk to 1 (Risk)
    y = df[target_col].map({"good": 0, "bad": 1})
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, 
        test_size=test_size, 
        random_state=random_state, 
        stratify=y
    )
    
    return X_train, X_test, y_train, y_test
